WITH grant_flex AS PROCEDURE ()
RETURNS VARCHAR NOT NULL
LANGUAGE SQL
AS
$$
BEGIN

   IF (UPPER('{{env}}') = 'DEV') THEN

      EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA COP_DMT_FLX TO ROLE DEV_CTRLCLD_USER';
      EXECUTE IMMEDIATE 'GRANT USAGE ON ALL PROCEDURES IN SCHEMA COP_DMT_FLX TO ROLE DEV_CTRLCLD_USER';
      EXECUTE IMMEDIATE 'GRANT ALL ON ALL PROCEDURES IN SCHEMA COP_DMT_FLX TO ROLE DEV_CTRLCLD_USER';
      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA COP_DSP_FLEX TO ROLE DEV_CTRLCLD_USER';
      EXECUTE IMMEDIATE 'GRANT ALL ON ALL SEQUENCES IN SCHEMA COP_DMT_FLX TO ROLE DEV_CTRLCLD_USER';
      EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA COP_DMT_FLX TO ROLE DEV_FLEX_POWERON_ROLE';
      EXECUTE IMMEDIATE 'GRANT ALL ON ALL PROCEDURES IN SCHEMA COP_DMT_FLX TO ROLE DEV_FLEX_POWERON_ROLE';
      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA COP_DMT_CCD TO ROLE DEV_CTRLCLD_USER';

      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA COP_DSP_CONTROLLING_CLOUD TO ROLE DEV_CTRLCLD_USER';
      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA COP_DSP_CONTROLLING_CLOUD TO ROLE DEV_CTRLCLD';

      EXECUTE IMMEDIATE 'GRANT USAGE ON STAGE COP_DMT_FLX.STG_FLX_TRF_FIL TO ROLE DEV_CTRLCLD_USER';
      EXECUTE IMMEDIATE 'GRANT USAGE ON STAGE COP_DMT_FLX.STG_FLX_TRF_FIL TO ROLE DEV_FLEX_POWERON_ROLE';

   ELSE

      EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON ALL TABLES IN SCHEMA COP_DMT_FLX TO ROLE {{env}}_CCL_USER';
      EXECUTE IMMEDIATE 'GRANT USAGE ON ALL PROCEDURES IN SCHEMA COP_DMT_FLX TO ROLE {{env}}_CCL_USER';
      EXECUTE IMMEDIATE 'GRANT ALL ON ALL PROCEDURES IN SCHEMA COP_DMT_FLX TO ROLE {{env}}_CCL_USER';
      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA COP_DSP_FLEX TO ROLE {{env}}_CCL_USER';
      EXECUTE IMMEDIATE 'GRANT ALL ON ALL SEQUENCES IN SCHEMA COP_DMT_FLX TO ROLE {{env}}_CCL_USER';
      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA COP_DMT_CCD TO ROLE {{env}}_CCL_USER';

      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA COP_DSP_CONTROLLING_CLOUD TO ROLE {{env}}_CCL';
      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA COP_DSP_CONTROLLING_CLOUD TO ROLE {{env}}_CCL_USER';

      EXECUTE IMMEDIATE 'GRANT USAGE ON STAGE COP_DMT_FLX.STG_FLX_TRF_FIL TO ROLE {{env}}_CCL_USER';
      EXECUTE IMMEDIATE 'GRANT USAGE ON STAGE COP_DMT_FLX.STG_FLX_TRF_FIL TO ROLE {{env}}_CCL';

   END IF;

   IF (UPPER('{{env}}') = 'PRD') THEN

      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA COP_DMT_CCD TO ROLE DEV_CTRLCLD_USER';
      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA COP_DSP_CONTROLLING_CLOUD TO ROLE DEV_CTRLCLD_USER';
      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA COP_DMT_CCD TO ROLE DEV_CTRLCLD';
      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA COP_DSP_CONTROLLING_CLOUD TO ROLE DEV_CTRLCLD';

      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA COP_DMT_CCD TO ROLE QAT_CCL_USER';
      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA COP_DSP_CONTROLLING_CLOUD TO ROLE QAT_CCL_USER';
      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL TABLES IN SCHEMA COP_DMT_CCD TO ROLE QAT_CCL';
      EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA COP_DSP_CONTROLLING_CLOUD TO ROLE QAT_CCL';

   END IF;

   EXECUTE IMMEDIATE 'GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA COP_DMT_FLX TO ROLE {{env}}_FLEX_POWERON';
   EXECUTE IMMEDIATE 'GRANT ALL ON ALL PROCEDURES IN SCHEMA COP_DMT_FLX TO ROLE {{env}}_FLEX_POWERON';
   EXECUTE IMMEDIATE 'GRANT ALL ON ALL SEQUENCES IN SCHEMA COP_DMT_FLX TO ROLE {{env}}_FLEX_POWERON';
   EXECUTE IMMEDIATE 'GRANT USAGE ON STAGE COP_DMT_FLX.STG_FLX_TRF_FIL TO ROLE {{env}}_FLEX_POWERON';
   EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA COP_DSP_FLEX TO ROLE {{env}}_FLEX_POWERON';
   EXECUTE IMMEDIATE 'GRANT SELECT ON ALL VIEWS IN SCHEMA COP_DMT_FLX TO ROLE {{env}}_FLEX_POWERON';
   
   RETURN 'GRANTS SUCCESS environement {{env}}';

END;
$$

CALL grant_flex();
