USE SCHEMA COP_DSP_FLEX;

CREATE OR REPLACE VIEW R_FLX_TTY_DIM_GRP
         (TTY_DIM_GRP_COD
         ,TTY_DIM_GRP_DSC
         )
AS
SELECT   FLX_GRP_COD   TTY_DIM_GRP_COD
        ,FLX_GRP_DSC   TTY_DIM_GRP_DSC
FROM     COP_DMT_FLX.R_FLX_GRP_DIM
WHERE    FLX_DIM_COD = 'TTY'
ORDER BY FLX_GRP_COD
/*
SELECT -1 CUS_TTY_GRP_COD,'Total Territory' TTY_DIM_GRP_DSC UNION ALL
SELECT  0 CUS_TTY_GRP_COD,'Territory'       TTY_DIM_GRP_DSC
*/
;

