USE SCHEMA COP_DSP_FLEX;

CREATE OR REPLACE VIEW R_FLX_ETI_DIM_GRP
         (ETI_DIM_GRP_COD
         ,ETI_DIM_GRP_DSC
         )
AS
SELECT   FLX_GRP_COD   ETI_DIM_GRP_COD
        ,FLX_GRP_DSC   ETI_DIM_GRP_DSC
FROM     COP_DMT_FLX.R_FLX_GRP_DIM
WHERE    FLX_DIM_COD = 'ETI'
ORDER BY FLX_GRP_COD
/*
SELECT -1 ETI_DIM_GRP_COD,'Total Entity' ETI_DIM_GRP_DSC UNION ALL
SELECT  0 ETI_DIM_GRP_COD,'Entity'       ETI_DIM_GRP_DSC UNION ALL
SELECT  1 ETI_DIM_GRP_COD,'Country'      ETI_DIM_GRP_DSC
*/
;

