USE SCHEMA COP_DSP_FLEX{{uid}};

CREATE OR REPLACE VIEW R_FLX_CUS_DIM_GRP 
         (CUS_DIM_GRP_COD
         ,CUS_DIM_GRP_DSC
         )
AS
SELECT   FLX_GRP_COD   CUS_DIM_GRP_COD
        ,FLX_GRP_DSC   CUS_DIM_GRP_DSC
FROM     COP_DMT_FLX.R_FLX_GRP_DIM
WHERE    FLX_DIM_COD = 'CUS'
ORDER BY FLX_GRP_COD

/*
SELECT -1 CUS_DIM_GRP_COD,'Total Customer' CUS_DIM_GRP_DSC UNION ALL
SELECT  0 CUS_DIM_GRP_COD,'Customer'       CUS_DIM_GRP_DSC UNION ALL
SELECT  1 CUS_DIM_GRP_COD,'L1 Customer'    CUS_DIM_GRP_DSC UNION ALL
SELECT  2 CUS_DIM_GRP_COD,'L2 Customer'    CUS_DIM_GRP_DSC UNION ALL
SELECT  3 CUS_DIM_GRP_COD,'L3 Customer'    CUS_DIM_GRP_DSC UNION ALL
SELECT  4 CUS_DIM_GRP_COD,'L4 Customer'    CUS_DIM_GRP_DSC UNION ALL
SELECT  5 CUS_DIM_GRP_COD,'L5 Customer'    CUS_DIM_GRP_DSC UNION ALL
SELECT  6 CUS_DIM_GRP_COD,'L6 Customer'    CUS_DIM_GRP_DSC
*/
;

