USE SCHEMA COP_DSP_FLEX;

CREATE OR REPLACE VIEW R_FLX_PDT_DIM_GRP
         (PDT_DIM_GRP_COD
         ,PDT_DIM_GRP_DSC
         )
AS
SELECT   FLX_GRP_COD   PDT_DIM_GRP_COD
        ,FLX_GRP_DSC   PDT_DIM_GRP_DSC
FROM     COP_DMT_FLX.R_FLX_GRP_DIM
WHERE    FLX_DIM_COD = 'PDT'
ORDER BY FLX_GRP_COD
/*
SELECT  -1 PDT_DIM_GRP_COD,'Total Product'          PDT_DIM_GRP_DSC UNION ALL
SELECT   0 PDT_DIM_GRP_COD,'Product'                PDT_DIM_GRP_DSC UNION ALL
SELECT   1 PDT_DIM_GRP_COD,'L1L Product Category'   PDT_DIM_GRP_DSC UNION ALL
SELECT   2 PDT_DIM_GRP_COD,'L2L Umbrella Brand'     PDT_DIM_GRP_DSC UNION ALL
SELECT   3 PDT_DIM_GRP_COD,'L3L Brand'              PDT_DIM_GRP_DSC UNION ALL
SELECT   4 PDT_DIM_GRP_COD,'L4L Product Family'     PDT_DIM_GRP_DSC UNION ALL
SELECT   5 PDT_DIM_GRP_COD,'L5L Product Sub-Family' PDT_DIM_GRP_DSC UNION ALL
SELECT   6 PDT_DIM_GRP_COD,'L6L Product Nature'     PDT_DIM_GRP_DSC UNION ALL
SELECT  10 PDT_DIM_GRP_COD,'L0 Product Category'    PDT_DIM_GRP_DSC UNION ALL
SELECT  11 PDT_DIM_GRP_COD,'L1 Product Area'        PDT_DIM_GRP_DSC UNION ALL
SELECT  12 PDT_DIM_GRP_COD,'L2 Umbrella Brand'      PDT_DIM_GRP_DSC UNION ALL
SELECT  13 PDT_DIM_GRP_COD,'L3 Product Brand'       PDT_DIM_GRP_DSC UNION ALL
SELECT  14 PDT_DIM_GRP_COD,'L4 Product Family'      PDT_DIM_GRP_DSC UNION ALL
SELECT  15 PDT_DIM_GRP_COD,'L5 Product Sub-Family'  PDT_DIM_GRP_DSC UNION ALL
SELECT  16 PDT_DIM_GRP_COD,'L6 Product Nature'      PDT_DIM_GRP_DSC UNION ALL
SELECT 101 PDT_DIM_GRP_COD,'L1 Platform Brand'      PDT_DIM_GRP_DSC UNION ALL
SELECT 102 PDT_DIM_GRP_COD,'L2 Brand'               PDT_DIM_GRP_DSC UNION ALL
SELECT 103 PDT_DIM_GRP_COD,'L3 Sub-Brand'           PDT_DIM_GRP_DSC
*/
;
