USE SCHEMA COP_DSP_FLEX;

CREATE OR REPLACE VIEW R_FLX_CUS_DIM
AS
SELECT   DISTINCT
         R_FLX_GRP_CUS.CBU_COD
        ,R_FLX_GRP_CUS.CUS_DIM_GRP_COD
        ,R_FLX_CUS_DIM_GRP.CUS_DIM_GRP_DSC
        ,R_FLX_GRP_CUS.CUS_GRP_COD
        ,R_FLX_GRP_CUS.CUS_GRP_DSC
        ,(CASE WHEN R_FLX_GRP_CUS.CUS_GRP_DSC LIKE 'TECH -%' THEN 1
               ELSE 0
          END)                                   AS TEC_CUS_FLG 
FROM     COP_DMT_FLX.R_FLX_GRP_CUS as r_flx_grp_cus
         INNER JOIN COP_DSP_FLEX.R_FLX_CUS_DIM_GRP AS R_FLX_CUS_DIM_GRP ON 
         (
            R_FLX_CUS_DIM_GRP.CUS_DIM_GRP_COD = R_FLX_GRP_CUS.CUS_DIM_GRP_COD
         )
ORDER BY 1, 2, 4;
