USE SCHEMA COP_DSP_FLEX{{uid}};

CREATE OR REPLACE VIEW R_FLX_PER_DIM_GRP
         (PER_DIM_GRP_COD
         ,PER_DIM_GRP_DSC
         )
AS
SELECT  -1 PER_DIM_GRP_COD,'Total Period' PER_DIM_GRP_DSC UNION ALL
SELECT   0 PER_DIM_GRP_COD,'Period'       PER_DIM_GRP_DSC UNION ALL
SELECT   1 PER_DIM_GRP_COD,'Month'        PER_DIM_GRP_DSC UNION ALL
SELECT   2 PER_DIM_GRP_COD,'Quarter'      PER_DIM_GRP_DSC UNION ALL
SELECT   3 PER_DIM_GRP_COD,'Semester'     PER_DIM_GRP_DSC UNION ALL
SELECT   4 PER_DIM_GRP_COD,'Full Year'    PER_DIM_GRP_DSC
;

