USE SCHEMA COP_DSP_FLEX{{uid}};

CREATE OR REPLACE VIEW R_FLX_EIB_DIM_GRP 
         (EIB_DIM_GRP_COD
         ,EIB_DIM_GRP_DSC
         )
AS
SELECT   FLX_GRP_COD   EIB_DIM_GRP_COD
        ,FLX_GRP_DSC   EIB_DIM_GRP_DSC
FROM     COP_DMT_FLX.R_FLX_GRP_DIM
WHERE    FLX_DIM_COD = 'EIB'
ORDER BY FLX_GRP_COD
/*
SELECT -1 EIB_DIM_GRP_COD,'Total EIB' EIB_DIM_GRP_DSC UNION ALL
SELECT  0 EIB_DIM_GRP_COD,'EIB'       EIB_DIM_GRP_DSC
*/
;

