USE SCHEMA COP_DSP_FLEX{{uid}};

CREATE OR REPLACE VIEW R_FLX_CAT_DIM_GRP 
         (CAT_DIM_GRP_COD
         ,CAT_DIM_GRP_DSC
         )
AS
SELECT   FLX_GRP_COD   CUS_DIM_GRP_COD
        ,FLX_GRP_DSC   CUS_DIM_GRP_DSC
FROM     COP_DMT_FLX.R_FLX_GRP_DIM
WHERE    FLX_DIM_COD = 'CAT'
ORDER BY FLX_GRP_COD
/*
SELECT -1 CAT_DIM_GRP_COD,'Total Category' CAT_DIM_GRP_DSC UNION ALL
SELECT  0 CAT_DIM_GRP_COD,'Category'       CAT_DIM_GRP_DSC
*/
;
