USE SCHEMA COP_DSP_FLEX;

CREATE OR REPLACE VIEW R_FLX_IND
(
    IND_ELM_COD
  , IND_ELM_DSC
  , IND_ORD_NUM
) 
AS
SELECT IND_ELM_COD
     , IND_ELM_DSP_DSC AS IND_ELM_DSC
     , IND_ORD_NUM
FROM COP_DMT_FLX.R_FLX_IND
WHERE IND_ELM_COD NOT IN ('GP_BY_NS', 'AP_WRK_BY_AP', 'PM_BY_NS', 'CM_BY_NS', 'ROP_BY_NS')  -- FQIE-115: Bug when denominator is a component of the numerator
ORDER BY IND_ORD_NUM;
