USE SCHEMA COP_DSP_FLEX{{uid}};

CREATE OR REPLACE VIEW P_FLX_SEC_CFG
(
    ID                    COMMENT 'ID FOR WRITEBACK'
    ,EML_USR_COD          COMMENT 'EMAIL OF THE USER WHO NEEDS SPECIAL AUTHORIZATIONS'
    ,USR_CAN_DEL_SCE_FLG  COMMENT '1 IF THE USER HAS PERMISSION TO REQUEST A SCENARIO DELETION'
) COMMENT = '[FLEX] FLEX PARAMETER TABLE FOR THE COGS FCA'
AS
SELECT
    ID
    ,EML_USR_COD
    ,CASE
        WHEN ROL_COD IN ('CAN_DEL_SCENARIO')
        THEN 1 ELSE 0 END AS USR_CAN_DEL_SCE_FLG
FROM COP_DMT_FLX{{uid}}.T_FLX_SEC_USR
;