USE SCHEMA COP_DMT_FLX{{uid}};

DROP TABLE IF EXISTS F_FLX_CMP_SCE;
DROP TABLE IF EXISTS F_FLX_SCE_IND;
DROP TABLE IF EXISTS F_FLX_SCE_INI;
DROP TABLE IF EXISTS F_FLX_SCE_INI_TNR;
DROP TABLE IF EXISTS F_FLX_SCE_SIM;
DROP TABLE IF EXISTS F_FLX_SRC_SCE_IND;
DROP TABLE IF EXISTS F_FLX_TGT_SCE;
DROP TABLE IF EXISTS R_FLX_CUR_RAT;
DROP TABLE IF EXISTS R_FLX_SRC_SCE_FLX;
DROP TABLE IF EXISTS W_FLX_SRC_SCE_FLT;
