USE SCHEMA COP_DMT_FLX{{uid}};

CREATE OR REPLACE TABLE R_FLX_SCE 
         (SCE_ELM_KEY                  VARCHAR(64)                          COMMENT 'Scenario Key : concatenation of CBU and Scenario Code'
         ,SCE_ELM_COD                  VARCHAR(50)                          COMMENT 'Scenario code (generated automatically)'
         ,SCE_ELM_DSC                  VARCHAR(50)                          COMMENT 'Scenario description'
         ,CBU_COD                      VARCHAR(10)                          COMMENT 'CBU/Market'
         ,CUR_COD                      VARCHAR(30)                          COMMENT 'Scenario input currency'
         ,SCE_YEA_COD                  NUMBER(10,0)                         COMMENT 'Scenario year'
         ,DTA_YEA_COD                  NUMBER(10,0)                         COMMENT 'Scenario Data year'                         
         ,SCE_PRO_COD                  VARCHAR(30)                          COMMENT 'Scenario process : RF01-R12/GPS01-GPS12...'
         ,LST_ACT_PER_COD              VARCHAR(10)                          COMMENT 'Last closed period'
         ,UPD_ACT_FLG                  NUMBER(2,0)                          COMMENT 'Flag requesting that the Actuals are updated (using ACT_SRC_SCE_COD) and the Gap closed upon scenario initialization'
         ,ACT_SRC_SCE_COD              VARCHAR(30)                          COMMENT 'Actual comparable scenario'
         ,CMP_1ST_SRC_SCE_COD          VARCHAR(30)                          COMMENT 'First comparable scenario'
         ,CMP_2ND_SRC_SCE_COD          VARCHAR(30)                          COMMENT 'Second comparable scenario'
         ,CMP_3RD_SRC_SCE_COD          VARCHAR(30)                          COMMENT 'Third comparable scenario'
         ,CRE_EML_USR_COD              VARCHAR(50)                          COMMENT 'Power BI user who created the scenario'
         ,CRE_END_TST                  TIMESTAMP                            COMMENT 'Date and time of creation of the scenario'
         ,INI_STS_COD                  VARCHAR(30)                          COMMENT 'Scenario initialization status: created > configuration_started > configured > init_in_progress > init_done | init_failed > '
         ,INI_RQT_FLG                  NUMBER(2,0)                          COMMENT 'Scenario configuration completion flag, it will chnage the status to configured and inittiate the process to populate scenario with Data'
         ,INI_RQT_TST                  TIMESTAMP                            COMMENT 'Date and time of the request of the initialization'
         ,INI_RQT_EML_USR_COD          VARCHAR(50)                          COMMENT 'Power BI user who requested the initialization of the scenario with the domain'
         ,INI_END_TST                  TIMESTAMP                            COMMENT 'Date and time the initialization process finished (changed to done or failed status)'
         ,CCD_STS_COD                  VARCHAR(30)                          COMMENT 'Scenario copy to Controlling Cloud status: flex_only > copy_requested > copy_done | copy_failed'
         ,CCD_RQT_FLG                  NUMBER(2,0)                          COMMENT 'Scenario request to send to CCD flag, it will change the status to copy_requested and inittiate the process to send the data back to snowflake'
         ,CCD_RQT_EML_USR_COD          VARCHAR(50)                          COMMENT 'Power BI user who requested the copy to Controlling Cloud'
         ,CCD_RQT_TST                  TIMESTAMP                            COMMENT 'Date and time of the request to copy to Controlling Cloud'
         ,CCD_END_TST                  TIMESTAMP                            COMMENT 'Date and time the copy process finished (changed to done or failed status)'
         ,DLT_STS_COD                  VARCHAR(30)                          COMMENT 'Deletion status: na > requested > in_progress > in_progress_step01 > in_progress_step02 > done | failed'
         ,DLT_RQT_FLG                  NUMBER(2,0) DEFAULT 0                COMMENT 'Flag indicating that a user has requested the scenario to be deleted (Power ON writeback)'
         ,DLT_RQT_TST                  TIMESTAMP                            COMMENT 'Date and time of the deletion request'
         ,DLT_RQT_EML_USR_COD          VARCHAR(50)                          COMMENT 'Email of the user who requested the deletion'
         ,DLT_END_TST                  TIMESTAMP                            COMMENT 'Date and time the deletion process finished (changed to done or failed status)'
         ,CUS_DIM_GRP_COD              NUMBER(10,0) DEFAULT 0               COMMENT 'Customer aggregation level'
         ,EIB_USE_FLG                  NUMBER(10,0) DEFAULT 0               COMMENT 'Business type/EIB aggregation level'
         ,TTY_USE_FLG                  NUMBER(10,0) DEFAULT 0               COMMENT 'Territory aggregation level'
         ,VAR_NS                       NUMBER(6,5)  DEFAULT 1               COMMENT 'Variability for the Net Sales (sensitivity to Volume sold)'
         ,VAR_MAT_COS                  NUMBER(6,5)  DEFAULT 1               COMMENT 'Variability for the Material Cost of Sales (sensitivity to Volume sold)'
         ,VAR_MAT_OTH                  NUMBER(6,5)  DEFAULT 1               COMMENT 'Variability for the Rest of Material Costs (sensitivity to Volume sold)'
         ,VAR_MANUF_COS                NUMBER(6,5)  DEFAULT 1               COMMENT 'Variability for the Manuf. Cost of Sales (sensitivity to Volume sold)'
         ,VAR_MANUF_OTH                NUMBER(6,5)  DEFAULT 1               COMMENT 'Variability for the Rest of Manuf. Costs (sensitivity to Volume sold)'
         ,VAR_LOG_FTC_IFO              NUMBER(6,5)  DEFAULT 1               COMMENT 'Variability for the Log. FTC IFO (sensitivity to Volume sold)'
         ,VAR_LOG_USL                  NUMBER(6,5)  DEFAULT 1               COMMENT 'Variability for the Log. Log USL (sensitivity to Volume sold)'
         ,VAR_LOG_OTH                  NUMBER(6,5)  DEFAULT 1               COMMENT 'Variability for the Rest of Log. Costs (sensitivity to Volume sold)'
         ,COGS_TOT_FCA_FLG             NUMBER(2,0)  DEFAULT 0               COMMENT 'FCA amount flag (amout > 0, 1 else 0)'
         ,SCE_CMT_TXT                  VARCHAR(5000)                        COMMENT 'Comment on the Scenario'
         ,SCE_CMT_TST                  TIMESTAMP                            COMMENT 'Date and Time of last modification of the comment'
         ,SCE_CMT_EML_USR_COD          VARCHAR(50)                          COMMENT 'Email of the user who modified the comment last'
         ,T_REC_DLT_FLG                NUMBER(2,0)                          COMMENT '[Technical] Physical deletion flag'
         ,T_REC_INS_TST                TIMESTAMP_TZ                         COMMENT '[Technical] Timestamp of first insertion into the table'
         ,T_REC_UPD_TST                TIMESTAMP_TZ                         COMMENT '[Technical] Timestamp of last update into the table'
         ,CONSTRAINT PK_R_FLX_SCE PRIMARY KEY (SCE_ELM_KEY)
         ) COMMENT = '[Flex] Flex scenario masterdata'
;
