USE SCHEMA COP_DMT_FLX{{uid}};

CREATE OR REPLACE TABLE R_FLX_PDT 
         (PDT_ELM_KEY                        VARCHAR(64)                         COMMENT 'Product Key : concatenation of CBU and Product Code'
         ,PDT_ELM_COD                        VARCHAR(30)                         COMMENT 'Product code'
         ,PDT_ELM_DSC                        VARCHAR(500)                        COMMENT 'Product name'
         ,CBU_COD                            VARCHAR(10)                         COMMENT 'CBU/Market'
         ,BRD_HIE_LV1_PTF_BRD_COD            VARCHAR(30)                         COMMENT 'Plateform code in the Brand Hierarchy (Level 1)'
         ,BRD_HIE_LV1_PTF_BRD_DSC            VARCHAR(500)                        COMMENT 'Plateform name in the Brand Hierarchy (Level 1)'
         ,BRD_HIE_LV2_BRD_COD                VARCHAR(30)                         COMMENT 'Brand code in the Brand Hierarchy (Level 2'
         ,BRD_HIE_LV2_BRD_DSC                VARCHAR(500)                        COMMENT 'Brand name in the Brand Hierarchy (Level 2'
         ,BRD_HIE_LV3_SUB_BRD_COD            VARCHAR(30)                         COMMENT 'Sub-Brand code in the Brand Hierarchy (Level 3)'
         ,BRD_HIE_LV3_SUB_BRD_DSC            VARCHAR(500)                        COMMENT 'Sub-Brand name in the Brand Hierarchy (Level 3)'
         ,LCL_HIE_LV1_PDT_ARE_COD            VARCHAR(30)                         COMMENT 'Product Area code in the Local Hierarchy (Level 1)'
         ,LCL_HIE_LV1_PDT_ARE_DSC            VARCHAR(500)                        COMMENT 'Product Area name in the Local  Hierarchy (Level 1)'
         ,LCL_HIE_LV2_UMB_BRD_COD            VARCHAR(30)                         COMMENT 'Umbrella Brand code in the Local  Hierarchy (Level 2)'
         ,LCL_HIE_LV2_UMB_BRD_DSC            VARCHAR(500)                        COMMENT 'Umbrella Brand name in the Local  Hierarchy (Level 2)'
         ,LCL_HIE_LV3_PDT_BRD_COD            VARCHAR(30)                         COMMENT 'Product Brand code in the Local  Hierarchy (Level 3)'
         ,LCL_HIE_LV3_PDT_BRD_DSC            VARCHAR(500)                        COMMENT 'Product Brand name in the Local  Hierarchy (Level 3)'
         ,LCL_HIE_LV4_PDT_FAM_COD            VARCHAR(30)                         COMMENT 'Product Family code in the Local  Hierarchy (Level 4)'
         ,LCL_HIE_LV4_PDT_FAM_DSC            VARCHAR(500)                        COMMENT 'Product Family name in the Local  Hierarchy (Level 4)'
         ,LCL_HIE_LV5_PDT_SFM_COD            VARCHAR(30)                         COMMENT 'Product Sub-Family code in the Local  Hierarchy (Level 5)'
         ,LCL_HIE_LV5_PDT_SFM_DSC            VARCHAR(500)                        COMMENT 'Product Sub-Family name in the Local  Hierarchy (Level 5)'
         ,LCL_HIE_LV6_PDT_NAT_COD            VARCHAR(30)                         COMMENT 'Product Nature code in the Local  Hierarchy (Level 6)'
         ,LCL_HIE_LV6_PDT_NAT_DSC            VARCHAR(500)                        COMMENT 'Product Nature name in the Local  Hierarchy (Level 6)'
         ,LV0_PDT_CAT_COD                    VARCHAR(30)                         COMMENT 'Product Category code in the Global Hierarchy (Level 0)'
         ,LV0_PDT_CAT_DSC                    VARCHAR(500)                        COMMENT 'Product Category name in the Global Hierarchy (Level 0)'
         ,LV1_PDT_ARE_COD                    VARCHAR(30)                         COMMENT 'Product Area code in the Global Hierarchy (Level 1)'
         ,LV1_PDT_ARE_DSC                    VARCHAR(500)                        COMMENT 'Product Area name in the Global Hierarchy (Level 1)'
         ,LV2_UMB_BRD_COD                    VARCHAR(30)                         COMMENT 'Umbrella Brand code in the Global Hierarchy (Level 1)'
         ,LV2_UMB_BRD_DSC                    VARCHAR(500)                        COMMENT 'Umbrella Brand name in the Global Hierarchy (Level 2)'
         ,LV3_PDT_BRD_COD                    VARCHAR(30)                         COMMENT 'Product Brand code in the Global Hierarchy (Level 3)'
         ,LV3_PDT_BRD_DSC                    VARCHAR(500)                        COMMENT 'Product Brand name in the Global Hierarchy (Level 3)'
         ,LV4_PDT_FAM_COD                    VARCHAR(30)                         COMMENT 'Product Family code in the Global Hierarchy (Level 4)'
         ,LV4_PDT_FAM_DSC                    VARCHAR(500)                        COMMENT 'Product Family name in the Global Hierarchy (Level 4)'
         ,LV5_PDT_SFM_COD                    VARCHAR(30)                         COMMENT 'Product Sub-Family code in the Global Hierarchy (Level 5)'
         ,LV5_PDT_SFM_DSC                    VARCHAR(500)                        COMMENT 'Product Sub-Family name in the Global Hierarchy (Level 5)'
         ,LV6_PDT_NAT_COD                    VARCHAR(30)                         COMMENT 'Product Nature code in the Global Hierarchy (Level 6)'
         ,LV6_PDT_NAT_DSC                    VARCHAR(500)                        COMMENT 'Product Nature name in the Global Hierarchy (Level 6)'
         ,T_REC_DLT_FLG                      NUMBER(2,0)                         COMMENT '[Technical] Physical deletion flag [BUT000.ODS_DELKZ (for SLT)]'
         ,T_REC_INS_TST                      TIMESTAMP_TZ                        COMMENT '[Technical] Timestamp of first insertion into the table'
         ,T_REC_UPD_TST                      TIMESTAMP_TZ                        COMMENT '[Technical] Timestamp of last update into the table'
         ,CONSTRAINT PK_R_FLX_PDT PRIMARY KEY (PDT_ELM_KEY)
         ) COMMENT = '[Flex] Product masterdata';
