USE SCHEMA COP_DMT_FLX;

UPDATE COP_DMT_FLX.F_FLX_SRC_SCE
SET CATEGORY_ELEMENT_CODE = 'MGR'
WHERE SRC_SCE_ELM_COD ILIKE '%ADD%'
AND CATEGORY_ELEMENT_CODE = 'NA'
;

UPDATE COP_DMT_FLX.F_FLX_MAN_SCE
SET CAT_TYP_ELM_COD = 'MGR'
WHERE MAN_SCE_ELM_COD ILIKE '%ADD%' 
AND CAT_TYP_ELM_COD = 'NA'
;