USE SCHEMA COP_DMT_FLX{{uid}};

MERGE INTO T_FLX_SEC USING (
    WITH
    _NEW_T_FLX_SEC (RSC_COD, ROL_COD, ROL_CAN_SEL_FLG, ROL_CAN_INS_FLG, ROL_CAN_UPD_FLG, ROL_CAN_DEL_FLG) AS (SELECT * FROM VALUES
    /*** BEGIN DATA ***/
    ('flex.r_flx_sce', '<DEFAULT>',        1, 1, 1, 0),
    ('flex.r_flx_sce', 'CAN_DEL_SCENARIO', 1, 1, 1, 1)
    /*** END DATA ***/
    ),
    _ALL_T_FLX_SEC (RSC_COD, ROL_COD, ROL_CAN_SEL_FLG, ROL_CAN_INS_FLG, ROL_CAN_UPD_FLG, ROL_CAN_DEL_FLG, T_REC_DLT_FLG) AS (
        SELECT *, 0 AS T_REC_DLT_FLG FROM _NEW_T_FLX_SEC
        UNION ALL
        SELECT RSC_COD, ROL_COD, ROL_CAN_SEL_FLG, ROL_CAN_INS_FLG, ROL_CAN_UPD_FLG, ROL_CAN_DEL_FLG, 1 AS T_REC_DLT_FLG
        FROM T_FLX_SEC
        WHERE NOT EXISTS (
            SELECT 1
            FROM _NEW_T_FLX_SEC
            WHERE T_FLX_SEC.RSC_COD = _NEW_T_FLX_SEC.RSC_COD
                AND T_FLX_SEC.ROL_COD = _NEW_T_FLX_SEC.ROL_COD
        )
    )
    SELECT * FROM _ALL_T_FLX_SEC

) AS _T_FLX_SEC ON (
        T_FLX_SEC.RSC_COD = _T_FLX_SEC.RSC_COD
        AND T_FLX_SEC.ROL_COD = _T_FLX_SEC.ROL_COD
    )
    WHEN MATCHED AND _T_FLX_SEC.T_REC_DLT_FLG = 1
        THEN DELETE
    WHEN MATCHED AND _T_FLX_SEC.T_REC_DLT_FLG = 0 AND (T_FLX_SEC.ROL_CAN_SEL_FLG <> _T_FLX_SEC.ROL_CAN_SEL_FLG OR T_FLX_SEC.ROL_CAN_INS_FLG <> _T_FLX_SEC.ROL_CAN_INS_FLG OR T_FLX_SEC.ROL_CAN_UPD_FLG <> _T_FLX_SEC.ROL_CAN_UPD_FLG OR T_FLX_SEC.ROL_CAN_DEL_FLG <> _T_FLX_SEC.ROL_CAN_DEL_FLG)
        THEN UPDATE SET T_FLX_SEC.ROL_CAN_SEL_FLG = _T_FLX_SEC.ROL_CAN_SEL_FLG, T_FLX_SEC.ROL_CAN_INS_FLG = _T_FLX_SEC.ROL_CAN_INS_FLG, T_FLX_SEC.ROL_CAN_UPD_FLG = _T_FLX_SEC.ROL_CAN_UPD_FLG, T_FLX_SEC.ROL_CAN_DEL_FLG = _T_FLX_SEC.ROL_CAN_DEL_FLG, T_FLX_SEC.T_REC_UPD_TST = current_timestamp
    WHEN NOT MATCHED
        THEN INSERT (RSC_COD, ROL_COD, ROL_CAN_SEL_FLG, ROL_CAN_INS_FLG, ROL_CAN_UPD_FLG, ROL_CAN_DEL_FLG, T_REC_DLT_FLG, T_REC_INS_TST, T_REC_UPD_TST) VALUES (_T_FLX_SEC.RSC_COD, _T_FLX_SEC.ROL_COD, _T_FLX_SEC.ROL_CAN_SEL_FLG, _T_FLX_SEC.ROL_CAN_INS_FLG, _T_FLX_SEC.ROL_CAN_UPD_FLG, _T_FLX_SEC.ROL_CAN_DEL_FLG, 0, current_timestamp, current_timestamp);
