USE SCHEMA COP_DMT_FLX{{uid}};

CREATE OR REPLACE TABLE T_FLX_REF_DEP 
         (PBI_SRC_TBL         VARCHAR(30)               COMMENT 'Table'
         ,PBI_DEP_TBL         VARCHAR(30)      NOT NULL COMMENT 'DependentTable'
         ,PBI_SAM_PAR         NUMBER(10,0)              COMMENT 'SamePartition'
         ,T_REC_INS_TST       TIMESTAMP_NTZ(9)
         ,T_REC_INS_USR       VARCHAR(100)
         ) COMMENT = '[Flex] This table using for refresh Power BI Semantic Model dependent table';

INSERT INTO T_FLX_REF_DEP (PBI_SRC_TBL,PBI_DEP_TBL) VALUES ('R_FLX_SCE','Scenario');
INSERT INTO T_FLX_REF_DEP (PBI_SRC_TBL,PBI_DEP_TBL) VALUES ('R_FLX_SCE','P_FLX_SCE_CFG_IND');
INSERT INTO T_FLX_REF_DEP (PBI_SRC_TBL,PBI_DEP_TBL) VALUES ('R_FLX_SCE','P_FLX_GAP_CLO_CFG');
INSERT INTO T_FLX_REF_DEP (PBI_SRC_TBL,PBI_DEP_TBL) VALUES ('R_FLX_SCE','P_FLX_ETI_PDT_FCA');
-- INSERT INTO T_FLX_REF_DEP (PBI_SRC_TBL,PBI_DEP_TBL) VALUES ('R_FLX_SCE','Ref_Scenario'); --Removed the 3rd July 2025 
INSERT INTO T_FLX_REF_DEP (PBI_SRC_TBL,PBI_DEP_TBL) VALUES ('R_FLX_SCE','R_FLX_SRC_SCE'); --Added the 3rd July 2025 
INSERT INTO T_FLX_REF_DEP (PBI_SRC_TBL,PBI_DEP_TBL) VALUES ('R_FLX_MAN_SCE','R_FLX_SRC_SCE'); --Added the 3rd July 2025 
